---
apiVersion: v1
kind: Secret
metadata:
  name: oncall-mariadb-secret
  namespace: oncall
type: Opaque
stringData:
  MYSQL_PASSWORD: "OncallDB2026!"
  MYSQL_ROOT_PASSWORD: "OncallRoot2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: oncall-redis-external
  namespace: oncall
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: oncall
    meta.helm.sh/release-namespace: oncall
type: Opaque
stringData:
  redis-password: "OnCallRedis2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: oncall-mysql-external
  namespace: oncall
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: oncall
    meta.helm.sh/release-namespace: oncall
type: Opaque
stringData:
  mariadb-root-password: "OncallDB2026!"
