---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oncall-gr-tls
  namespace: oncall
spec:
  dnsNames:
    - oncall.cloudless.gr
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: oncall-gr-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oncall
  namespace: oncall
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.middlewares: oncall-oncall-admin-chain@kubernetescrd,kube-system-hsts@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: oncall.cloudless.gr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oncall-engine
                port:
                  number: 8080
  tls:
    - hosts:
        - oncall.cloudless.gr
      secretName: oncall-gr-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oncall-webhooks
  namespace: oncall
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "20"
    traefik.ingress.kubernetes.io/router.middlewares: oncall-oncall-webhook-chain@kubernetescrd,kube-system-hsts@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: oncall.cloudless.gr
      http:
        paths:
          - path: /integrations/
            pathType: Prefix
            backend:
              service:
                name: oncall-engine
                port:
                  number: 8080
  tls:
    - hosts:
        - oncall.cloudless.gr
      secretName: oncall-gr-tls
